# Generated by Django 2.1 on 2018-08-30 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Год'),
        ),
    ]
