# Generated by Django 2.1 on 2018-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Blog', '0003_auto_20180831_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.TextField(blank=True, null=True, verbose_name='tracklist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
    ]
